### ISSUE TITLE
Replace deprecated `build-url` package with native`new URL`

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#2058] opened 2023-05-08 10:23 UTC
## Problem

We are using `build-url` package to create the URLs for the external sources. It is deprecated:
` WARN  deprecated build-url@6.0.1: This package is no longer maintained`

## Description

We can replace it with the native `URL`.

**Comment by krysal** [comment] 2023-06-04 19:47
Duplicate of #2139.

**Closed by krysal** 2023-06-04 19:47 UTC
Labels: help wanted, 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code, 🧱 stack: frontend
