### ISSUE TITLE
Cutting a release does not successfully run CI/CD workflow

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#976] opened 2023-03-21 03:32 UTC
## Description

I cut a release in anticipation of deploying the production API today. My understanding of the production deployment process was:

1. Cut a release
2. Wait for CI/CD to pass and publish the images
3. Run the workflow for the production API deployment with the release name as the image tag

However, step 2 never passes: https://github.com/WordPress/openverse/actions/runs/4475172448

I knew we'd deployed production recently, so I looked at the production API deployment workflow logs and saw that we'd just been deploying production to a SHA.

@zackkrida you're the only one I saw doing this so I'm pinging you as I'm not sure who else to ask: did you know that this process was broken (is this a known issue)? Was it decided that we would deploy production API and Nuxt to SHAs rather than release version tags?

If that is the case... should we do away with the "release" process altogether?

Additionally, I'll need to know if this is the case in order to update #907 with that information.

cc @AetherUnbound and @dhruvkb as y'all have the most time working on the workflow files, maybe y'all will know the details here.

## Additional context

Marking as critical because not having a clearly documented production release process is a recipe for disaster. If someone who didn't know where to look to find out how to do this otherwise needed to deploy production in an emergency, they'd be lost, and quite unjustly so.

**Comment by zackkrida** [comment] 2023-03-21 14:47
## History

There is a very valid decision to be made about how we handle (or do not handle) releases, but I believe this is a misunderstanding of how the deployment actions have historically worked.

To use the [old frontend](https://github.com/wordpress/openverse-frontend) as an example, we deployed in two ways:

- The [rollback workflow](https://github.com/WordPress/openverse-frontend/actions/runs/3170950742/workflow), which released an existing tag and didn't evoke CI.
- The [GitHub Container Registry & Deployment workflow](https://github.com/WordPress/openverse-frontend/actions/runs/4207805818/workflow) which also never evoked CI before building images. You can see in this [search view](https://github.com/WordPress/openverse-frontend/actions?query=event%3Arelease++) that releases have only ever triggered build actions, never CI.

Neither of those evoke CI before building the images and I don't believe they ever have. 

Each built image has been through the CI pipeline as a prerequisite for being merged into `main`. Given that, we should be able to assume that _all_ built images in the container registry are valid deployment targets.

## Recent API deploys and decisions

The only production deploys I've done recently were during the triage of the production database CPU incident. I chose to use SHAs for ease of potentially multiple, experimental deployments to production. It's purely coincidental. There was no official decision to use shas. 

In the last "official" (not related to an incident) deployment of the API, the release process did build and tag the images correctly:

https://github.com/WordPress/openverse/actions/runs/4367187713

## Moving forward

A "release", should we choose to use them, would only be for the purposes of associating a human-readable numerical nickname and a list of deployed changes with an existing image. I see this entirely as something meant to benefit maintainers and/or users. We _could_ build the images for extra security, if desired, but we could also simply tag the `latest` version of an image with the release version number upon publishing a release. The `latest` version of the image has already been through CI and would be a duplicate of the version created and tagged by the release process.

So to me, the open questions are:

1. Do we want to use releases? Do we find them useful to ourselves and users?
2. Do we use a single version number (CalVer) for each release, or do we need different semver version numbers per-stack? I.E, one for the API, one for the frontend.
3. If we use releases, do they need to build and run CI on the images, or can they simply tag the `latest` image instead?

**Comment by sarayourfriend** [comment] 2023-03-21 22:23
> Neither of those evoke CI before building the images and I don't believe they ever have.

I didn't mean to imply that the previous process _did_ evoke CI. However, the new workflow most certainly depends on CI/CD to build the images, as, as you pointed out, image building and publishing is no longer a separate workflow that could be triggered on release.

Part of the confusion here is that we now have one massive CI/CD workflow that manages "all the things" so discrete parts are difficult to reference.

> If we use releases, do they need to build and run CI on the images, or can they simply tag the latest image instead?

I don't think they need to run tests and linting or to build a new image, provided the merge to main has already done these things.

> Do we want to use releases? Do we find them useful to ourselves and users?

The only thing I know they're useful for is to identify the list of changes. However, the current draft release workflow isn't useful for this as all changes are grouped together, making it difficult to find the changes relevant to a particular application.

Which also brings up the other point, which is that the GitHub release feature cuts it for everything in the monorepo. It's probably worth it then to not use GitHub's "Releases" feature. Instead, we could have a simple workflow for tagging the images for a specific application with the release tag (CalVer, SemVer, whatever we want), and collecting the changes relevant to that application (probably via the "stack" labels).

> Recent API deploys and decisions

Thanks for the context, it sounds like this was not a known issue then. That makes me think that whatever process we _do_ decide on, we should also establish an expectation for verifying it works if changes are made to it.

My summarised suggestion, then, is just this: stop using GitHub releases and create our own "Tag application" workflow for tagging the images for a given app. The workflow should gather the changes for the stack between the previous "release tag" and report them somewhere. No opinion on the format of tag to use but CalVer makes the most sense to me for reasons I've shared various times elsewhere, but basically amount to that our only public API is the Django API and that has versioned API endpoints which serve as our publicly dependable "versions".

**Comment by dhruvkb** [comment] 2023-03-22 07:59
The main issue with GitHub Releases or Git tags is that they are associated with a commit. Said commit could be a vital milestone for any layer of the stack but for others, it would be meaningless. In fact, if nothing has changed for a particular layer, we would still be publishing a new image with a new version and publishing it. Additionally, it forces every layer to be on the same version number as identified by the release name or Git tag.

I have one approach to this that gives us a way to address each image with a human-readable, strictly increasing version number while allowing us to keep each layer independent: using version numbers from [`package.json`](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#version) and [`pyproject.toml`](https://peps.python.org/pep-0621/#version).

Consider this approach where we **do not use GitHub Releases**.

On every push to `main`, the CI+CD workflow performs these steps:
- builds images that are tagged with the SHA hash of the commit
- triggers staging deployment for the affected services
  - passes the SHA of the commit as the workflow input

If the commit message contains a changed `package.json` or `pyproject.toml` file, the CI+CD workflow also does one additional step:
- triggers production deployment for the affected services
  - passes the updated version version as the workflow input

We can continue to do a manual rollback by passing the last known good version and manually triggering the prod deployment workflow.

**Comment by zackkrida** [comment] 2023-03-22 19:33
> My summarised suggestion, then, is just this: stop using GitHub releases and create our own "Tag application" workflow for tagging the images for a given app. The workflow should gather the changes for the stack between the previous "release tag" and report them somewhere. No opinion on the format of tag to use but CalVer makes the most sense to me for reasons I've shared various times elsewhere, but basically amount to that our only public API is the Django API and that has versioned API endpoints which serve as our publicly dependable "versions".

This feels quite right to me, @sarayourfriend! Then a deploy would be two steps, to run the tag action followed by the deployment action, using the same tag for both. 

@dhruvkb's solution is similar, but a bit more manual. This step:

> If the commit message contains a changed package.json or pyproject.toml file, the CI+CD workflow also does one additional step

would also need to parse _only_ changes in the version number, not the entire file, and that seems a bit burdensome to maintain.

As for where to store changelogs, it'd be really cool to get them on a page on https://docs.openverse.org. But published _anywhere_ would be fine to start.

**Comment by dhruvkb** [comment] 2023-03-22 19:44
Parsing changes in version number is not very difficult considering we can run Python scripts inside workflow jobs. But I have no attachment towards my approach and would be okay if we went another way. docs.openverse.org is an awesome place to host docs, cheers to that.

**Comment by sarayourfriend** [comment] 2023-03-22 22:05
I started a PR here (https://github.com/WordPress/openverse/pull/987) that implements the workflow based idea. I like Dhruv's approach as well, and I think it's a fine way to encode the milestones in a place in code relevant to the particular application. The workflow I developed in the PR could be easily adapted for that use case. I think a lot of what I've already worked on would be useful here, in particular generating the changelogs for each application stack and putting them in a changelogs directory. We can put the changelogs in the documentation easily, just move the output folder in the workflow :slightly_smiling_face:

**Comment by sarayourfriend** [comment] 2023-03-22 23:45
The PR https://github.com/WordPress/openverse/pull/987 is updated to reflect the conversation thus far with two outstanding questions in the PR description. We can move the discussion there if folks are okay with the approach I've taken. If not I can close that PR and we can decide on what specific other approach to take.

**Closed** 2023-03-26 23:15 UTC
Labels: 🟥 priority: critical, 🛠 goal: fix, 🤖 aspect: dx, 🧱 stack: mgmt
