### ISSUE TITLE
sessionStorage permissions on the frontend

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#2673] opened 2023-07-18 22:51 UTC
## Description

Sometimes for various reasons, `window.sessionStorage` is inaccessible. This can lead to `Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.` errors relating to our feature flags.

Sentry issue: https://openverse.sentry.io/share/issue/2f0cd99b8bca4bebb1a4034f49687bc6/

We should address this, perhaps by checking for `sessionStorage` access in our `useStorage` composable, or by ignoring the error. There isn't really anything we can do when sessionStorage is inaccessible.

**Comment by sarayourfriend** [comment] 2023-07-19 00:40
We use `@vueuse/core`'s `useStorage` composable. This should theoretically be fixed: https://github.com/vueuse/vueuse/issues/1105

Except on the PR it looks like someone else is also encountering the issue: https://github.com/vueuse/vueuse/issues/2534#issuecomment-1537851808

We're on 9.3.0 though, which is 10 months old and predates that PR that fixed the issue. It might be enough to fix this issue by just upgrading our vueuse dependency. We should try that at least before making code-changes on our end to handle the error.

**Comment by dhruvkb** [comment] 2023-07-19 02:10
This is a duplicate of #2563.

**Closed** 2023-07-19 11:12 UTC
Labels: 🚦 status: awaiting triage, 🛠 goal: fix
