### ISSUE TITLE
Image table contains `.ogv` videos

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#4717] opened 2024-08-05 16:06 UTC
## Description

Wikimedia script ingests `.ogv` video files as images. We should filter them out and probably also drop the ones we already added from the catalog database.

## Reproduction

1. Go to https://openverse.org/image/2dc93cee-34d6-4b98-a76e-92ebc8d4ae73?q=phytoplankton+bloom
2. The main image is unavailable, as are most of the related images.
3. If you go to the source, you will see that this is actually a video of `.ogv` extension.

## Additional context

These images were noticed by @sarayourfriend in #4665

**Comment by sarayourfriend** [comment] 2024-08-06 10:02
The structured data for this result on Wikimedia shows the media type as `application/ogg`.

That's actually interesting, because I don't know how you would disambiguate that from an audio file if you don't have the extension in the URL!

https://commons.wikimedia.org/w/index.php?curid=59122955

At least in this case, we do have the direct file URL and can use the extension from it.

**Comment by obulat** [comment] 2024-08-06 10:33
> That's actually interesting, because I don't know how you would disambiguate that from an audio file if you don't have the extension in the URL!

In the Wikimedia API result, this media is probably marked as image in the `mediatype` key of the response:
https://github.com/WordPress/openverse/blob/23467c8d57b593a758aac43cd20211e49a927fdb/catalog/dags/providers/provider_api_scripts/wikimedia_commons.py#L450

We [accept as image](https://github.com/WordPress/openverse/blob/23467c8d57b593a758aac43cd20211e49a927fdb/catalog/dags/providers/provider_api_scripts/wikimedia_commons.py#L145) all media that is marked as `"BITMAP"` or `"DRAWING"`. It appears that some of the media marked with those values are of `application/ogg` type, so we should be filtering them out.

**Comment by sarayourfriend** [comment] 2024-08-06 12:16
It's good to note that "image", in some metadata standards (DublinCore, for example) includes both moving and still images. Something to keep in mind, especially when interfacing with GLAM institutions that may be using terms like that in their metadata.

I'm surprised wikimedia considers those bitmaps or drawings, though 🙂 bitmap doesn't seem to me as generic as "image", though I suppose it can be if interpreted loosely, which it already is anyway!

**Comment by krysal** [comment] 2024-08-16 16:34
Code changes are prepared in #4772, and I confirmed there are 45397 of these items in Wikipedia incorrectly classified.

```sql
openledger=> SELECT COUNT(*) FROM image WHERE source = 'wikimedia' AND url ~ '^.*.(ogv)$';
 count
-------
 45397
```

I want to proceed with cleaning up manually by running an update similar to the one used in #1796.

```sql
DELETE FROM image WHERE source = 'wikimedia' AND url ~ '^.*.(ogv)$';
```

@WordPress/openverse-catalog Can I get a second review on this? I don't think they need to be kept separate but what do you think?

**Comment by sarayourfriend** [comment] 2024-08-19 01:45
@krysal for what it's worth, `LIKE` might be faster for a simple suffix match (`url LIKE '%.ogv'`) and prevents easy-to-miss regex bugs like missing the escape on the second period. `^.*.(ogv)$` will match any string ending in "ogv" with any one or more character prefix, not just those ending in ".ogv". A simpler pattern match approach would avoid that complexity entirely and is worth using in contexts like these if only for that simplicity. Also, as written, the query is case sensitive, have you confirmed that's okay? `~*` is case insensitive (or `ILIKE`/`~~*` if you decide to switch to a simpler pattern match). Wikimedia Commons does not appear to normalise file extensions to lowercase, [here's an example of a capitalised GIF extension (warning: flashing lights in the animation)](https://commons.wikimedia.org/wiki/File:Yellow_Flash_Light_A.GIF).

Are OGV the only video types Wikimedia considers images? Wanted to make sure we aren't missing a greater issue based on the ogv examples we originally found by accident. I don't even see ogv listed in this image file format listing page: https://commons.wikimedia.org/wiki/Category:Images_by_file_format. It also isn't in their file type dropdown on their own search: https://commons.wikimedia.org/w/index.php?search=&title=Special:MediaSearch&go=Go&type=image

It seems like we should report these videos as incorrectly categorised to Wikimedia Commons, right? In which case, we need to extract these into a CSV before deleting them.

**Comment by krysal** [comment] 2024-08-19 15:19
@sarayourfriend Thanks for bringing that up! I overlooked the case sensitivity, which is funny because I was exactly finding a lot of weird case extensions here (`'Jpg', 'JPg', 'jPG', 'jpG', 'JPG', 'jpeg', 'jPeG', 'Jpeg', 'JPEG', 'png', 'Png', 'pnG', 'PNG'` and the list go on...); you're right, and I like the more uncomplicated pattern match as well :) 

> Are OGV the only video types Wikimedia considers images? 

I don't know, but they might have fixed that categorization. The few rows I looked at were all ingested in 2020 (the maximum date is pending to get the query result). Would you want me to store them in a separate table before deleting them?

The updated instruction would be:

```sql
DELETE FROM image WHERE source = 'wikimedia' AND url ILIKE '%.ogv';
```

PD: I'm also working on your comments in #4772.

**Comment by sarayourfriend** [comment] 2024-08-21 23:42
PDFs might be okay, at least from Wikimedia, provided they are mostly PDFs representing _images_ rather than text (they are sometimes used as a wrapper around TIFF or JPEG scans)? We are able to get thumbnails of them from Wikimedia now, and they can be used as images in many contexts (imported easily into editors like Photoshop, GIMP, etc). The example from the issue works now. It feels more on the edge to me than videos, which are definitely _not_ images in the sense we use that word (still images).

**Comment by krysal** [comment] 2024-08-23 23:38
After a more extensive scan, I found many more files incorrectly ingested in the `image` table from Wikimedia.

<details>
<summary>query</summary>

```sql
SELECT extension, COUNT(extension)
FROM (
    SELECT LOWER(RIGHT(url, 4)) AS extension FROM image
    WHERE source = 'wikimedia' AND url NOT ILIKE ALL(ARRAY[
        -- well known image types
        '%.apng', '%.avif', '%.bmp', '%.ico', '%.jpg', '%.jpeg', '%.png', '%.gif', '%.svg', '%.tif', '%.tiff', '%.webp',
    ])
) AS tmp_ext
GROUP BY 1;
```

Sidenote: It's a shame we can't use negative indexes in the Postgres' split_part` function. It is available from v14.

</details>

```sql
 extension | count
-----------+-------
 djvu      |   918
 .mid      |    17
 midi      |     3
 mpeg      |     2
 .mpg      |    65
 .ogg      |   124
 .ogv      | 45401
 .pdf      | 50144
 .stl      |   904
 .wav      |    26
 webm      |    34
 .xcf      |  1263
(12 rows)
```

From that list, 3 types are technically classified as images.

| file type | visible in openverse | sample link |
| -- | -- | -- |
| .djvu | ✅ | https://openverse.org/image/e141c4e0-239b-4c67-80d0-d5cce5d8d08c |
| .stl | ❌ | https://openverse.org/image/9fadc89c-e08f-455c-b645-52c3250bf470 |
| .xcf | ❌ | https://openverse.org/image/054b17fa-fdd7-42bb-a1a4-8989fbe4a074 |

We render .djvu files correctly, but .stl and .xcf files are not shown on the image detail page in Openverse. It would be cool to show those 3D models of Wikimedia (.stl), though I'm not sure what to do with the .xcf files.

Regarding pdf, I'll vote for removing them, they're ocasionally displayed on Openverse, like while navigating between related results, because of the cached thumbnail but going to the indiviual page directly does not show them, eg. [pdf1](https://openverse.org/image/774f598f-4da2-4601-996c-3e6688dc8852), [pdf2](https://openverse.org/image/d6a42c55-7ecb-4c73-8ede-ffdd505c9d24). Try refreshing one of the related images that is a PDF. It will also complicate type validations. Will that mean that potentially, a .xls or other doc type containing an image should also be allowed? Before going that deep, it's better to avoid that by adding more first-class media types (videos, 3D models, documents).

For now, I exported these wrong rows from Wikimedia into the `s3://openverse-catalog/deletions/wikimedia_non_images_2024-08-23.tsv` file @sarayourfriend, and removed them from upstream except for PDFs, waiting to get feedback on this discussion. If the file is not required anymore (given @obulat's clarification in [this comment](https://github.com/WordPress/openverse/pull/4785#issuecomment-2301909971)), feel free to delete it. I also created a snapshot with today's date before running the delete. Below, you can find all the SQL instructions.

<details>
<summary>query</summary>

```sql

-- Confirmation of numbers of rows to export to s3 and then delete

SELECT extension, COUNT(extension) FROM (
    SELECT LOWER(RIGHT(url, 4)) AS extension FROM image
    WHERE source = 'wikimedia' AND url ILIKE ANY(ARRAY[
        -- known non-image types
        '%.mid',
        '%.midi',
        '%.mpeg',
        '%.mpg',
        '%.ogg',
        '%.ogv',
        '%.pdf',
        '%.wav',
        '%.webm'
    ])) AS tmp_ext
GROUP BY 1;

extension | count
-----------+-------
 .mid      |    17
 midi      |     3
 mpeg      |     2
 .mpg      |    65
 .ogg      |   124
 .ogv      | 45401
 .pdf      | 50144
 .wav      |    26
 webm      |    34
(9 rows)


-- export
SELECT * FROM aws_s3.query_export_to_s3(
    'SELECT foreign_landing_url, url FROM image WHERE source = ''wikimedia'' AND (url ILIKE ANY(ARRAY[''%.mid'', ''%.midi'', ''%.mpeg'', ''%.mpg'', ''%.ogg'', ''%.ogv'', ''%.pdf'', ''%.wav'', ''%.webm'']))',
    'openverse-catalog',
    'deletions/wikimedia_non_images_2024-08-23.tsv',
    'us-east-1'
);


extension | count
-----------+-------
 .mid      |    17
 midi      |     3
 mpeg      |     2
 .mpg      |    65
 .ogg      |   124
 .ogv      | 45401
 .wav      |    26
 webm      |    34
(8 rows)

-- removal (skipping .pdf)
DELETE FROM image WHERE source = 'wikimedia' AND url ILIKE ANY(ARRAY['%.mid', '%.midi', '%.mpeg', '%.mpg', '%.ogg', '%.ogv', '%.wav', '%.webm']);

DELETE 45672

```

</details>

---

Pending is to decide what to do with the `.stl ` and `.xcf` and `.pdf` rows.

**Comment by zackkrida** [comment] 2024-08-26 15:16
My recommendations are:

- `.stl` files: Keep them, show the thumbnail on the single result page but add some text somewhere like "View in 3D at the source"
- `.xcf` files: Figure out how to show a larger PNG preview on the single result view.

**Comment by obulat** [comment] 2024-08-26 15:38
I would also vote for removing pdf and djvu files because they are often multi-page documents. We can display them once we add "books" as another format :)

I like the recommendations for `stl` and `xcf`. I tried to understand if Sketchfab Viewer can be used with `stl`, but couldn't find it in the documentation. Do you know, @zackkrida ?

**Comment by zackkrida** [comment] 2024-08-26 15:45
@obulat it only works with models hosted on Sketchfab.

**Comment by sarayourfriend** [comment] 2024-08-26 23:23
Of these formats we are discussing, the only one Wikimedia considers a bitmap is XCF. Everything else is not an image according to MediaWiki's classification. Why would we keep any of these incorrectly ingested works? We will not ingest any _new_ PDFs, STLs, etc, due to filtering on MediaWiki's classification of BITMAP and AUDIO.

Thanks to @obulat for the link to the list of media types from them: https://doc.wikimedia.org/mediawiki-core/master/php/MimeMap_8php_source.html

Can STL be used as an image? If not, and image search is for finding images to use, I don't see how 3d models connect to that purpose. Similar to why we excluded ogv even though we can create a thumbnail. PDF is the same, even if it _can_ be an image, MediaWiki isn't holding only PDF images. We incorrectly ingested those.

Dejavu are ebooks, not images. I can't see them in my browser (Firefox or Chromium), and again, it is hard to understand how that fits into the remit of "image search".

The suggestion for XCF makes sense because it is an image format that can be used as an image. This is definitely a separate GitHub issue to implement that, though. @zackkrida since you made the suggestion, can you create the issue for improving XCF display on the single result page? Using the thumbnail URL for the single result page of XCF files and passing `full_size=True` and `compressed=False` should be enough to solve that for the frontend.

To refocus on the core of this issue, which is to deal with these bad records in the database. Is all that is left to delete the works we don't want to keep, right? @krysal can you share an updated query that would do that? Would it be more reliable to select every ending that is _not_ one of the BITMAPs in the MediaWiki code, so we know we've found everything that we would not today ingest from Wikimedia as an image?

**Comment by zackkrida** [comment] 2024-08-27 12:44
> @zackkrida since you made the suggestion, can you create the issue for improving XCF display on the single result page?

Sure thing!

Concerning STL, I suggested displaying thumbnails on the single result page because this is precisely what we do for [Thingiverse](https://openverse.org/image/collection?source=thingiverse). For [Sketchfab](https://openverse.org/image/collection?source=sketchfab), another 3D model provider currently included with our images, we have special logic to display their model viewer on the single result pages.

It would certainly be preferable to move these works into a "3D Model" content type, even if we don't yet have a 3D model viewer for the non-Sketchfab results. Still, having Sketchfab, Wikimedia Commons, and Thingiverse results is already a fairly robust 3D model collection, so perhaps this work is warranted sooner than later (even if marked as "beta" or a similar designation). 

All of that is to day: my thinking was that even if it isn't ideal, following the existing precedence for handling 3D models as images, for now, might better set us up for the future.

**Comment by AetherUnbound** [comment] 2024-08-27 17:15
Chiming in to say I agree with the recommendations above, namely:
* Exclude `.pdf`, for the reasons Krystle mentions.
* Try to support `.xcf` if we can.
* Hold off on including `.stl` for now. While we do include Thingiverse & Sketchfab, this would be another source of data we'd need to move over to 3D models when that time comes and we don't _have_ to include it under images. That's a loosely held opinion though, given that we have precedence, I would not object to including them as well.

**Comment by krysal** [comment] 2024-08-28 22:41
> Of these formats we are discussing, the only one Wikimedia considers a bitmap is XCF.

> Dejavu are ebooks, not images. I can't see them in my browser (Firefox or Chromium), and again, it is hard to understand how that fits into the remit of "image search".

@sarayourfriend .djvu is also considered images by Wikimedia: `'image/vnd.djvu' => [ 'djvu,' 'div' ]` and the Python's `mimetypes`lib. However, I wrongly assumed that they render correctly in my case, it's the same as `.xcf` in that I was looking at the thumbnail instead of the actual file. I'm unsure what to do with this tho, given these facts.

As to .stl, my reasoning for keeping them was similar to Zack's: We could give them a similar treatment to Sketchfab and Thingiverse. I thought we could put them in a separate table, but a frontend workaround might be easy and good enough. Maybe what you suggest can apply too to .djvu files?

> To refocus on the core of this issue, which is to deal with these bad records in the database. Is all that is left to delete the works we don't want to keep, right? @krysal can you share an updated query that would do that? Would it be more reliable to select every ending that is not one of the BITMAPs in the MediaWiki code, so we know we've found everything that we would not today ingest from Wikimedia as an image?

I made that query in [this comment](https://github.com/WordPress/openverse/issues/4717#issuecomment-2307927998), that's how I find out what remained to be removed. I can run the same again to confirm of course. I'll response back when that finishes, and make the issue for XCF display.

**Comment by sarayourfriend** [comment] 2024-08-29 02:45
> I made that query in https://github.com/WordPress/openverse/issues/4717#issuecomment-2307927998, that's how I find out what remained to be removed

Gosh, I'm sorry! I totally missed the fact that "query" was a collapsed summary/details block and interpreted it as introducing the table of results below it. You've covered the bases then, never mind me!

> Maybe what you suggest can apply too to .djvu files?

Do you mean the suggestion to use the thumbnail? I've just tried loading the example djvu result you shared and this time it loaded! Before I only got a broken file:

![image](https://github.com/user-attachments/assets/f0b472d6-c8f6-42c3-be9a-596704511a66)

However, the link of the image being rendered is actually the thumbnail link (https://api.openverse.org/v1/images/e141c4e0-239b-4c67-80d0-d5cce5d8d08c/thumb/). I didn't think to look before, so I don't know if when it didn't load whether there was an issue with the thumbnail or if it was trying to load the actual file.

In any case, it does look like Wikimedia's thumbnails endpoint works for it, so the approach Zack suggested of using a larger version of the thumbnail should work. So yes, your suggestion to use the same strategy for djvu seems good, if we keep those files :+1: 

### Further consideration on DjVu files

On the other hand, it's _very_ interesting that they are considered images but not PDFs, because if you visit the example file on Wikimedia, you can go through the individual pages of the book. I can see a justification for us keeping djvu files if they are always collections of images (instead of PDFs which can be mixed images and text). It would match the fact that we have scanned pages of books from Biodiversity Heritage Library, for example. If we keep them, we should plan to do some additional work to improve how we index and/or display them. That work could have multiple phases ranging in complexity.

To begin with, we should indicate that additional pages may be available by visiting the source and that only the first page is displayed on Openverse. That would be in addition to updating the handling of djvu files to match the suggestion for XCF.

Beyond that, we could index each individual page (as with BHL), and connect them as part of a collection of images. The ability to do that is something I've touched on being necessary to improve the handling of book scans and other types of directly related images (#1290 #2992). That approach would be of immediate benefit to BHL (which has severe data quality issues, I mention in the #1290 discussion) and other "scans of books" sources like #1742. It's a lot of work and goes down to a data architecture level, plus significant design and UI implementation concerns (not to mention careful consideration for search). It would be either one huge project to cover all aspects of this, or a series of smaller projects. Maybe start with data architecture changes, including thinking about the needs described in #1290; then move on to UI design, implementation, and search considerations. It's huge.

All of that is possible, but none of it is blocked on the smaller improvement. I agree with your suggestion to give djvu images the same thumbnail-based display treatment as XCF, and suggest also adding more context to the single result pages for djvu to indicate the special considerations for them (multiple pages).

I added handling djvu image display the same as XCF to the XCF issue you created. [I've also created an issue to cover adding the necessary context about djvu](https://github.com/WordPress/openverse/issues/4834).

Finally, I created [a stub issue for the data architecture project](https://github.com/orgs/WordPress/projects/70/views/1?pane=issue&itemId=77357316), and another for [improving the display of multi-image works like ebooks](https://github.com/orgs/WordPress/projects/70/views/1?pane=issue&itemId=77364695).

**Comment by AetherUnbound** [comment] 2024-09-04 22:28
I have seen this and will respond to this discussion when I have time!

**Comment by krysal** [comment] 2024-09-12 18:54
I ran the SQL to remove the remaining PDF files and confirmed that the image table is clean. The .stl files are still there, waiting for a more explicit action/consensus, but I think we can close this issue since it has expanded its reach much further than initially anticipated.

**Closed** 2024-09-12 18:55 UTC
Labels: 🟨 priority: medium, 🛠 goal: fix, 🧱 stack: catalog, 🗄️ aspect: data
