### ISSUE TITLE
Auckland Museum

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#2598] opened 2023-07-10 07:50 UTC
### Source Site

https://www.aucklandmuseum.com/discover/collections/our-data

### Value Provided

High quality collections and data

### Licenses Provided

Not everything is openly licensed but some things are PDM or CC: https://www.aucklandmuseum.com/legal/rights-and-permissions

### Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by obulat** [comment] 2023-10-24 06:32
Closing as duplicate of #1771. Thank you for noticing, @ngken0995!

**Closed by obulat** 2023-10-24 06:32 UTC
Labels: 🟩 priority: low, 🧹 status: ticket work required, 🌟 goal: addition, 💻 aspect: code, 🧱 stack: catalog, ☁️ provider: images
