### ISSUE TITLE
Theme selector with previous dark theme colors

### ISSUE THREAD

**Issue by fcoveram** [WordPress/openverse#5215] opened 2024-11-29 10:26 UTC
## Description

On staging, I noticed that after changing from system (default) to dark, the component kept showing the previous color scheme (dark pink shade).

## Reproduction

https://github.com/user-attachments/assets/23888d27-182f-4c84-888c-a151be1e6251

1. Go to staging.openverse.org
2. On homepage's footer, click on the theme select
3. Select "Dark"
4. Click out of the component to unfocus
5. See the color mismatch

**Comment by dhruvkb** [comment] 2024-11-29 12:03
This is specific to Safari so I have reduced the priority to low.

**Comment by obulat** [comment] 2024-12-04 06:47
@dhruvkb, why doesn't Safari store cookies? That would be a big problem for rendering, wouldn't it?

**Comment by obulat** [comment] 2024-12-04 06:49
One more problem I can see in Safari: the select becomes white inside on the light mode.
![Image](https://github.com/user-attachments/assets/fb4ac8e1-c85e-45b7-98ea-824c36a0deb9)

I've also noticed it being pink in the dark (or system, I'm not sure now) mode in Arc, but I couldn't reliably reproduce it.
![Image](https://github.com/user-attachments/assets/73037857-62b6-40c5-a5c1-3a11b7ef35cb)

**Comment by dhruvkb** [comment] 2024-12-04 06:59
I have not observed this problem at all in Arc or Firefox but it does occur in Safari. That's because Safari does not handle `click` events on `<select>`. I've pushed a fix for Safari in PR #5216 to use `focus` event instead of `click`, which also works on other browsers.

As for the cookies, after debugging this for an entire day, all I could tell is that Safari is very finicky about cookies (in the name of privacy) and does not store any cookies for Openverse.org at all. It's receiving the cookies in the response, parsing them too but then discarding them instead of storing. I need to try this again without extensions to be certain it's not one my extensions that's responsible for this behaviour.

**Closed** 2024-12-04 07:38 UTC
Labels: 🟩 priority: low, 🛠 goal: fix, 🕹 aspect: interface, 🧱 stack: frontend
