### ISSUE TITLE
Replace `requests` mocking with `pook`

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#2256] opened 2023-06-01 00:48 UTC
## Current Situation

`pook` is a library introduced in the API test suite. We have an issue to introduce it to the catalog in https://github.com/WordPress/openverse/issues/1938, however there are other places we should refactor in the API test suites as well.

## Suggested Improvement

Refactor the following test modules to replace `requests` mocking with `pook`.

> *Note*
> Some places may not be able to rely entirely on `pook`, if we're testing weird `requests` edge cases that cannot be triggered by changes in the HTTP response. Those should be explicitly documented when they're needed.

- [x] `test_photon`
- [ ] `test_watermark`
- [ ] `test_waveform`
- [ ] `test_image_views`
- [x] `test_slack` (ingestion server)

## Benefit

Using `pook` makes the expected HTTP response more explicit, meaning the tests are clearer. Mocking `requests` (because we mock the various HTTP verb methods, `get`, `post`, `head`, etc) relies on understanding the specific behaviour requests exhibits under certain HTTP request lifecycle conditions. Using `pook` removes that reliance, creating a test suite that is more resilient long-term to changes in the behaviour of the `requests` library. It also reduces our reliance on `requests` as the specific library we use, which could change if we switch to ASGI Django, for example.

**Comment by ashiramin** [comment] 2023-06-12 20:10
@sarayourfriend Can I take this up? haven't used `pook` before so should be good way to learn

**Comment by zackkrida** [comment] 2023-06-12 21:04
Please, go ahead and give it a shot, @ashiramin! If you run into any issues just leave us a comment here or [find us in the #openverse channel of the Making WordPress Slack instance.](https://make.wordpress.org/chat/#joining)

**Comment by ashiramin** [comment] 2023-06-17 04:28
@zackkrida I can set up mocking with for non binary data but it seems like `pook` doesn't support binary https://github.com/h2non/pook/issues/55

**Comment by ashiramin** [comment] 2023-08-06 03:14
@zackkrida @sarayourfriend Finally got around to this Got busy with life Please take a look and let me know what you think https://github.com/WordPress/openverse/pull/2783

**Comment by dhruvkb** [comment] 2023-09-27 06:31
3/5 of the listed usages of mocking have not yet been resolved so the issue is kept open.

**Comment by ngken0995** [comment] 2023-10-19 16:37
@sarayourfriend @dhruvkb can i work on this?

**Comment by dhruvkb** [comment] 2023-10-19 18:03
Sure, please go ahead @ngken0995!

**Comment by ngken0995** [comment] 2023-10-20 18:49
@dhruvkb I realize pook maintainers hasn't reviewed @sarayourfriend PR to support binary https://github.com/h2non/pook/pull/88.

**Comment by dhruvkb** [comment] 2023-10-21 02:52
Yeah `pook` hasn't had any activity in 9 months so I'm not entirely sure if it is even maintained anymore. 

One way to proceed would be to change our `pook` dependency to point to @sarayourfriend's version as in PR #3236. I'm not sure if that's the right approach so we can block this issue till either h2non/pook#88 or #3236 are merged.

**Comment by dhruvkb** [comment] 2023-10-26 08:43
@ngken0995 we merged #3236 so now we can use the latest features from pook without having to wait for the next release. Feel free to work on this issue if you're interested.

**Comment by ngken0995** [comment] 2023-10-26 12:51
@dhruvkb Yes, I'll continue to work on this.

**Comment by ngken0995** [comment] 2023-10-31 19:44
@dhruvkb I'm not sure if i'm going on the right path. 

I tried to edit the `_default_response_factory` function and got an error about unexpected keyword `binary`. Take a look at the error below:
 
```
    def _default_response_factory():
        res : pook.Mock = (
            pook.Response()
            .header("headers", _MOCK_AUDIO_INFO["headers"])
>           .body(body=BytesIO(_MOCK_AUDIO_BYTES), binary=True).mock
            )
E       TypeError: Response.body() got an unexpected keyword argument 'binary'

```
Am I going on the right track?

**Comment by sarayourfriend** [comment] 2023-10-31 21:19
@ngken0995 Can you confirm you ran `pipenv install` in the `api` directory to get the updated dependency?

**Comment by dhruvkb** [comment] 2023-11-01 05:44
Adding to @sarayourfriend's suggestion, you might also need to rebuild and recreate the `web` container.

```console
$ just dc build web
$ just dc up -d --force-recreate web
```

**Comment by ngken0995** [comment] 2023-11-01 18:02
@sarayourfriend @dhruvkb Thank you, running the following command above worked.

**Closed** 2023-12-22 15:47 UTC
Labels: help wanted, 🟩 priority: low, 💻 aspect: code, 🧰 goal: internal improvement, 🐍 tech: python, 🧱 stack: api, 🧱 stack: ingestion server
