### ISSUE TITLE
Filter and blur sensitive results by term matching

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#377] opened 2023-02-06 19:18 UTC
| Start Date | Project Lead    | Actual Ship Date |
| ---------- | --------------- | ---------------- |
| 2023-02-06 | @sarayourfriend | TBD              |

## Description

This project matches Openverse images against a list of sensitive terms. All sensitive single image results on the frontend are blurred and viewing them is opt-in for all users.

Development work is ongoing and tracked in a milestone: https://github.com/WordPress/openverse/milestone/12

## Documents

- [x] [Trust and Safety in the Openverse: Preliminary User Stories and Exploration](https://docs.openverse.org/projects/proposals/trust_and_safety/20230109-trust_and_safety_preliminary_overview_and_exploration.html) - A general doc relevant to all content safety projects
- [x] [Project Proposal](https://docs.openverse.org/projects/proposals/detecting_sensitive_textual_content/20230309-project_proposal_detecting_sensitive_textual_content.html)
- [Implementation Plans (link to requested plans)](https://docs.openverse.org/projects/proposals/detecting_sensitive_textual_content/20230309-project_proposal_detecting_sensitive_textual_content.html#required-implementation-plans)
  - [x] https://github.com/WordPress/openverse/pull/911
    - This wasn't noted as a requested IP in the project proposal as it was already being worked on by Zack, but it is part of this project.
  - [x] https://github.com/WordPress/openverse/issues/937
    - [Milestone here](https://github.com/WordPress/openverse/milestone/5)
  - [x] https://github.com/WordPress/openverse/issues/938
- [x] [Design Proposal](https://github.com/WordPress/openverse/issues/791)

## Issues

- [x] #854 
- [x] #1169 
- [x] API Milestone: https://github.com/WordPress/openverse/milestone/5
- [x] Frontend Milestone: https://github.com/WordPress/openverse/milestone/12

## Prior Art

- https://github.com/WordPress/openverse-api/pull/1108 | A potential full-fledged implementation for the API
- https://github.com/WordPress/openverse/issues/750
- https://github.com/WordPress/openverse/issues/721

**Comment by zackkrida** [comment] 2023-03-07 18:42
## Update 2023-03-07



Frontend design work is taking place here. This work assumes that the MVP of this functionality will allow the user to show sensitive results, and to elect to blur sensitive results in the search results view (with blurring as the default value). 

We also assume the MVP of this functionality does _not_ display or allow the user to enable _specific_ sensitive content subcategories. However, this active design work will be easily adaptable and compatible with such functionality if we decide to include it.

### Done



- Francisco created a design proposal (#791) and we have been soliciting feedback.

### Next



- [ ] #854 @dhruvkb is going to implement a solution which enables developers to mark arbitrary search results as sensitive for the purposes of testing blurring without requiring developers to look at _actual_ sensitive content.
- [ ] @panchovm will share an update to the design proposal for additional commentary and approval

### Blockers



I have been delayed in publishing my recommendations for a sensitive content terms list for Openverse, but will do so by the end of the week.

**Comment by sarayourfriend** [comment] 2023-03-08 04:55
@zackkrida This project currently has the "In RFC" status, but it looks like that means we're skipping the project planning step of this. Is that intentional? I want to clarify before I get to deeply into writing the implementation plan.

**Comment by sarayourfriend** [comment] 2023-03-08 07:09
> This work assumes that the MVP of this functionality will allow the user to show sensitive results, and to elect to blur sensitive results in the search results view (with blurring as the default value).

Further clarification: are these _separate_ features? Is this re-wording of the quoted summary accurate? "We will enhance our data for what a "sensitive" result might be, thereby filtering them out of queries that do not have `mature=True`. Additionally, when `mature=True` and we are including results with sensitive terms, then we will by default blur those results until the user designates that they do not want the blurred results."

The part I want to clarify here is whether we expect results with sensitive terms to appear in queries where mature is not `True` (i.e., the default query) or if blurred results would only appear for when `mature=True`.

**Comment by zackkrida** [comment] 2023-03-08 16:34
@panchovm and I decided that it might be best to pause design work after soliciting feedback on the latest iteration of the design. This is primarily to prevent us from having to make further assumptions that may contradict the upcoming planning documents. The designs are in a place where some preliminary development can start (or resume, considering #824) behind a feature flag while we continue to plan.

**Comment by sarayourfriend** [comment] 2023-03-08 23:55
Thanks for the clarifications on all accounts. They sound great. I've got about half a technical implementation plan written for this, it turns out the most difficult part will probably be designating which results have sensitive terms in their textual content in the search API in a way that does not degrade performance.

I'll write the kickoff post first and get the project planning generally started. Having technical implementation plans is a good idea here. Blurring likely deserves its own consideration unless we decide to just use regular CSS blurring, but it's something we can discuss in the kickoff discussion.

**Comment by panchovm** [comment] 2023-03-09 10:23
After addign the [second part of iteration two (i2)](https://github.com/WordPress/openverse/issues/791#issuecomment-1461686489), I blocked the design ticket (#791) until this project concludes the design scope.

**Comment by sarayourfriend** [comment] 2023-03-17 01:28
The project proposal has been merged and the implementation plan request issues have been created. Both are currently blocked by different things:

- API is blocked by resolving the discussion with Elasticsearch experts about how best to implement the filtering
- Frontend is blocked needing the designs

Both IPs could have some aspects written without resolving these blockers first. However, both are blocked on core aspects of their functionality, so I think it makes sense to truly wait until we've resolved the blockers before starting on them.

Thanks to @krysal and @AetherUnbound for the quick reviews on the project proposal (it was merged 1 week before its deadline) and thanks to @panchovm, @obulat, @cogdog, and @zackkrida for additional reviews and comments.

**Comment by sarayourfriend** [comment] 2023-03-21 04:14
Noting here that the ETA for this project is not a reasonable estimate for completion and folks keeping track should not expect it by then. We still haven't resolved the questions blocking the API implementation plan and the designs are not yet available for the frontend. Writing and discussing those implementation plans could realistically take until the end of March and then implementation will only start afterwards. I think a more realistic ETA is the end of April.

**Comment by zackkrida** [comment] 2023-04-11 22:19
I've reached out to maintainers of the WordPress GitHub org to create a new repo for the sensitive terms list. I made [this post](https://make.wordpress.org/openverse/2023/04/11/new-repository-for-storing-sensitive-terms/) on our Make blog to provide them with context.

I've also created a new group called @WordPress/openverse-sensitive-content-reviewers who will be responsible for reviewing the text contents of the new repo.

**Comment by sarayourfriend** [comment] 2023-04-11 23:26
Update: project proposal is approved and merged. The first implementation plan is being reviewed #996.

**Comment by sarayourfriend** [comment] 2023-05-28 23:08
There have been two significant changes to parts of this project:

1. The ingestion server now accepts an environment variable with the URL where it can find the sensitive terms list rather than the sensitive terms list itself. This makes it slightly easier to manage a huge list and reduces the configuration complexity (Terraform doesn't need to download the file and update it and to get a new list we just update the remote file rather than need to redeploy the ingestion server).
2. In the process of working on [the `sensitivity` field for the API query response](https://github.com/WordPress/openverse/pull/2057) I discovered that we do not actually ingest any sensitivity information from providers. The plan originally assumed that we did and designs reflected that in some copy that stated that the provider marked a result as sensitive. Not needing to cover this case _significantly_ reduced the complexity of the implementation of the sensitivity field. As part of a related project's implementation plan to change `mature` to `sensitive` (https://github.com/WordPress/openverse/pull/2126), we may be able to remove the overloaded meaning of the single `mature` field on the Elasticsearch documents and use more explicit names like `provider_marked_sensitive` and `user_reported_sensitive` for our sensitivity boolean properties on documents. In any case, the current approach works perfectly for us to derive whether a result has a confirmed user report or sensitive text, the only two cases that actually exist in our data[^1]

[^1]: The fact that we do not re-ingest data from Flickr or other providers that have sensitive results and will not get updated information if one of those works is marked sensitive _after_ our initial ingestion of it. There's nothing we can do about this now. It is its own massive project and falls under similar stuff as the #417.

We need to make an infrastructure change to add the new ingestion server environment variable for the sensitive terms list URL, then we can run the filtered index creation DAG.

**Comment by sarayourfriend** [comment] 2023-06-01 02:08
I've just finished deploying the ingestion server. It now has the configuration for the sensitive terms list. The next time filtered index creation runs (on the next audio refresh) we should be able to see if the terms list is working as expected.

**Comment by zackkrida** [comment] 2023-06-05 21:10
@sarayourfriend Madison has identified an issue with the API side of this project here: https://github.com/WordPress/openverse/issues/2328

**Comment by sarayourfriend** [comment] 2023-06-05 23:03
Thanks, Zack. I left a comment on the issue (Madison pinged me there too). This might introduce significant delays in this project depending on the avenue we decide to take in that issue. I'll update here again once we have a clearer idea of which path we'll pursue.

**Comment by sarayourfriend** [comment] 2023-06-20 01:33
No progress has been made on this project since the last update. As mentioned before, the frontend implementation plan was approved, but issues still need to be created the for the plan's related milestone (linked in the issue description) by @dhruvkb. The primary reasons for the stall on this project are AFKs, conferences, and the several recent API incidents taking attention away from ongoing projects.

**Comment by zackkrida** [comment] 2023-06-27 21:24
@dhruvkb I've set you as the lead for this one moving forward. I'll be happy to help with the implementation in the coming month, as well as the remaining issue creation later this week.

CC @sarayourfriend

**Comment by zackkrida** [comment] 2023-07-11 14:16
@sarayourfriend and @dhruvkb a few questions:

1. I don't think we have `ENABLE_FILTERED_INDEX_QUERIES` enabled in the production and staging APIs. I see it set to true in our `env.template` but not in the infrastructure repo or our task definitions. Should it be? (I think so 😄)
3. By what criteria should we make the API param `unstable__include_sensitive_results` stable? I assume it can go live prior to the frontend implementation.

**Comment by sarayourfriend** [comment] 2023-07-11 21:25
> I don't think we have ENABLE_FILTERED_INDEX_QUERIES enabled in the production and staging APIs. I see it set to true in our env.template but not in the infrastructure repo or our task definitions. Should it be? (I think so smile)

Production filtered image index creation needs to successfully finish before that can be turned on in production (and staging). There is an open incident report for the production data refresh that involves issues with the filtered index creation. I haven't looked deeply into what y'all discovered after I logged off yesterday, but if there's anything that still needs tweaking/fixing in that DAG, then we should do so before turning on filtered index queries in production.

> By what criteria should we make the API param unstable__include_sensitive_results stable? I assume it can go live prior to the frontend implementation.

I originally intended it to remain unstable until the frontend feature was complete and ready to be turned on. It is prudent to wait to stabilise the API feature until we have confirmed that its current implementation fulfils the requirements and expectations of our own use case on the frontend. Once the frontend feature flag is ready to be turned on for production, we can stabilise the parameter and the search result `unstable__sensitivity` property, update references to such on the frontend, and then turn the feature on for production frontend.

Of course, that relies on filtered index queries being on in production as well, so we need to resolve any issues with the DAG, as mentioned above.

**Comment by zackkrida** [comment] 2023-07-11 21:30
Thanks! 

> Once the frontend feature flag is ready to be turned on for production, we can stabilise the parameter and the search result unstable__sensitivity property, update references to such on the frontend, and then turn the feature on for production frontend.

Sounds perfect 👍 

Concerning the filtered index dag, the problem has been identified and Madison is working on a fix:

https://github.com/WordPress/openverse/issues/2619

I'll recommend that we add `ENABLE_FILTERED_INDEX_QUERIES` and deploy on Monday, provided that issue is fixed first.

**Comment by zackkrida** [comment] 2023-07-24 14:47
There are open PRs for the single result views. The blurring of search results was merged.

Open PRs:

- #2700 
- #2651

**Comment by zackkrida** [comment] 2023-08-01 17:17
@dhruvkb, @fcoveram raised some thoughts about the overall flow. I thought I'd have time to create dedicated issues for these, but alas, I don't think I will. Perhaps we should have a sync session after our team meetup to address these:

## New potential issues

- [ ] Consider blurring in the global audio player
- [ ] Fix global audio player on error pages
- [ ] Safety wall content and styling updates
  - Determine final text. (Do we need “Would you like to view the page?” for example?
  - Replace "Back to results" label with "Go to search" when the user didn't navigate from a search
  - Implement new layout for center-aligned texts

## Discussions

- The amount of blur: should it be smaller on smaller devices?
- Dedicated page vs. adding an "About page" section for explaining sensitive content (we planned on a page originally)

**Comment by dhruvkb** [comment] 2023-08-02 02:39
I think a sync session with @fcoveram, and the team, at the meetup will be helpful, I'll make issues for these post that.

**Comment by fcoveram** [comment] 2023-08-02 07:39
Noting that the following two points were part of the agreed design.
* Blurring image in the global audio player
* "Go to search" label in primary button on walled page when landing from an openverse link

**Comment by zackkrida** [comment] 2023-08-02 12:26
One other idea for that sync session:

- Should we show the eye-closed icon on top of the blurred results? I noticed google does this and it _does_ seem clearer:




![Image](https://github.com/WordPress/openverse/assets/6351754/5581c877-c972-4945-bfc1-7db6ed005bdd)

![Image](https://github.com/WordPress/openverse/assets/6351754/f0fb1482-3d84-405d-936e-81619fffdd93)

**Comment by fcoveram** [comment] 2023-08-02 12:53
I also like Google's solution, but there are other product-wise considerations pointed out [here](https://github.com/WordPress/openverse/issues/791#issuecomment-1503047920). But definitely something to keep in mind.

**Comment by zackkrida** [comment] 2023-08-02 13:38
I am thinking of the icon like a label, rather than proposing any changes to the flow or behavior. 

There are certain contexts where the blur alone may not be a strong enough visual cue, like the following results:

![Screenshot_20230802-093719.png](https://github.com/WordPress/openverse/assets/6351754/5a0ad64a-3661-47e5-9f08-c346d2292251)

**Comment by fcoveram** [comment] 2023-08-03 08:21
Oh, I see. You are right. The interface needs to provide more context. Good point.

**Comment by dhruvkb** [comment] 2023-08-18 14:18
I am not sure the global player needs to be blurred because for it to appear, the user must click a result, choose to unblur that result from the content safety wall, see everything in the single result view, play the audio and then go back to all results. After this has happened, the result item itself is unblurred so the global player playing that item need not be blurred.

As for the eye icon on the blurred images, I would be in favour of a visual context but I am not sure what the best way to indicate this is. @fcoveram your input is appreciated in what the best UI would be to indicate that an image has been blurred for sensitivity and is not an actual blurry image (like a gradient).

**Comment by fcoveram** [comment] 2023-08-21 15:33
### Global player

> I am not sure the global player needs to be blurred because for it to appear, the user must click a result, choose to unblur that result from the content safety wall, see everything in the single result view, play the audio and then go back to all results. After this has happened, the result item itself is unblurred so the global player playing that item need not be blurred.

I agree with this. I'm referring to the flow when users play a blurred audio track _in_ the search results page. If the item has not been unblurred, and you click on play, the global player should also show blurred info. In other words, global player should mirror the audio track state.

Here is a quick prototype of this flow.

https://github.com/WordPress/openverse/assets/895819/482b62c5-f7fd-4bca-910b-1eb2965708e0

### Icon indicator

I tried different styles for the icon, and a black icon over a white layer with 60% opacity might work. The ratio contrast required for graphics is lower than for texts. However, the consistency between media types is my main concern.

After testing some ideas, I concluded that the designed consent flow (landing in the search results and enabling the sensitive results) is sufficient for conveying why some content (images and texts) is blurred. The change in the results area is very clear in that new content was added.

**Comment by dhruvkb** [comment] 2023-09-06 11:39
The project is very close to completion, with a total of 5 tickets, including 1 blocked ticket (#2550 that needs legal input) and 3 that already have PRs associated with them.

The API ticket for `sensitivity` in single results #2926 is the biggest blocker to roll-out so getting it assigned and resolved is the next priority item.

**Comment by sarayourfriend** [comment] 2023-09-07 18:40
I'm reaching out to the legal team again to ask for clarification on when we can expect a response. The last time I asked they didn't respond :confused:

**Comment by dhruvkb** [comment] 2023-09-25 06:55
The latest on this is that we have heard back from legal and these discussions brought up some actionable items:

1. wording changes in the draft document
2. wording changes for "mature" to "sensitive" in our products
3. additional features for the moderation tools project

@sarayourfriend has already implemented points 1 and 2 (thanks! 👏) so I think it should be time to formalise the text into a page on Openverse.org.

**Comment by dhruvkb** [comment] 2023-10-10 04:52
This has been shipped to production 🎈 🥳 🎉 ! One issue #3081 remains in the milestone blocked on the official translations to be written for the content safety explanation page.

**Comment by dhruvkb** [comment] 2023-10-12 19:19
The last issue in the milestone has also been resolved now. The project is shipped!

**Closed** 2023-10-12 19:19 UTC
Labels: 🌟 goal: addition, 🕹 aspect: interface, 🧭 project: thread, 🧱 stack: api, 🧱 stack: frontend

**Comment by AetherUnbound** [comment] 2023-12-06 04:05
I've drafted an announcement post for the feature here: [Google Docs Link](https://docs.google.com/document/d/1ehsYa9-tVmyfsejNDZiuw9ag1DyTuD0eYkchbnJ2KCg/edit). @dhruvkb and @WordPress/openverse-maintainers - please take a look and let me know if it sounds okay! I can post it this week and we can move this to "Success" 😄 🚀

**Comment by fcoveram** [comment] 2023-12-06 08:54
I will share the document with [rmartinezduque](https://github.com/rmartinezduque) asking for feedback.

**Comment by rmartinezduque** [comment] 2023-12-07 13:30
Congrats on shipping this new feature! The post looks great to me. I think it clearly communicates the new feature and the benefits it brings. I only suggested a few minor edits, mostly to correct a grammar mistake. If possible, I think it would also be nice to include an image to accompany the announcement (perhaps you already have it in mind). 🙂

**Comment by fcoveram** [comment] 2023-12-07 15:32
I can work on a visual for the post ⭐

**Comment by AetherUnbound** [comment] 2023-12-12 00:03
Our announcement P2 has been made: https://make.wordpress.org/openverse/2023/12/11/introducing-enhanced-content-safety-features-on-openverse/

And I've also made an amplification request for the marketing team here: https://github.com/WordPress/Marketing-Team/issues/330

With that, I'm going to move this project to "Success"!
