### ISSUE TITLE
Flake in all visual tests which conditionally render components with svg icons

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#2377] opened 2023-06-09 21:28 UTC
## Description

Any test which renders a new piece of UI mid-test which contains SVG icons can be subjected to flake in which the icons do not appear visually. Annoyingly, the Playwright trace viewer shows the SVG is "rendered" in the dom, but the link in the "use" blocks of these sprite-based SVGs do not appear to be loaded.

This is very likely likely related to #2135 from @obulat but feels very difficult to fix. I've spent hours investigating today and haven't been successful.

## Reproduction

Some examples of runs with this issue:

- #2357
  - https://github.com/WordPress/openverse/actions/runs/5225969431?pr=2376
- On main, another component this applies to is ` e2e/header-internal.spec.ts:83:9 › Header internal › screen at breakpoint xs with width 340 › content page opened from home should be scrollable `: https://github.com/WordPress/openverse/actions/runs/5226301308/jobs/9436844836

## Environment

- Device: 
- OS: 
- Browser: 
- Version: 
- Other info:

**Comment by obulat** [comment] 2023-06-10 04:04
> This is likely related to https://github.com/WordPress/openverse/pull/2135 from @obulat but feels very difficult to fix. I've spent hours investigating today and haven't been successful.

Since we can't see the SVG icons, that change is the first that comes to mind. Yet, if #2135 caused this issue, flakiness would show up more in the PRs right after it, and there are several frontend PRs that were merged after it without any SVG flakiness. And also, #2135 had changed the non-icon SVGs (the logo, brand, etc.), the icons were converted in an earlier PR.

I have no idea about how, but maybe the Playwright fixture addition changed something? Because that's the most recent Playwright-related change that is closer to the start of SVG-related flakiness. I'm going to try reverting it, and the test skip PR to see if there are any failures. I'm not sure how to check if flakiness is gone, though: if the CI passes - does it mean that the problem is fixed, or that we didn't get the problematic result _this time_? If the tests pass, I'll just re-run them to try to get them to fail again.

**Closed** 2023-06-10 18:22 UTC
Labels: 🟥 priority: critical, 🛠 goal: fix, 🤖 aspect: dx, 🧱 stack: frontend
