### ISSUE TITLE
Slack notification when CI/CD fails on main

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#1064] opened 2023-03-29 16:20 UTC
## Problem

When CI/CD is failing on main, we may not notice. This can give false confidence in some of our automations, and cause us to incorectly assume things like our staging sites and documentation sites are up to date.

## Description

Capture any failed CI/CD steps and send a Slack notification upon failure.

**Comment by AetherUnbound** [comment] 2023-03-29 18:52
Isn't this a duplicate of https://github.com/WordPress/openverse/issues/1032?

**Comment by zackkrida** [comment] 2023-03-29 18:56
Oops! I'll close

**Closed** 2023-03-29 18:56 UTC
Labels: 🟨 priority: medium, 🌟 goal: addition, 🤖 aspect: dx, 🧱 stack: mgmt
