### ISSUE TITLE
Automatically warn or convert unformatted URLs in the documentation site

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#4208] opened 2024-04-25 17:41 UTC
## Description

Context: #4173 and #4195 

We issued a one-off change to update all links in the [DAGs documentation](https://docs.openverse.org/catalog/reference/DAGs.html) page, but it's likely that we will encounter the issue of unclickable links in documentation in the future.

We should build out either a Sphinx plugin or a Vale linting rule to handle these cases, and either warn when a link is unformatted (e.g. `http://{link}` instead of the correct `<http://{link}>`) or automatically convert those links into the formatted version.

@sarayourfriend may be able to provide context on the Vale approach.

For the Sphinx approach, we could use something like our existing extensions which automatically [link GitHub usernames](https://github.com/WordPress/openverse/blob/331b576ad8dd99dc00c6a777a3b3addc6dbd3225/documentation/_ext/link_usernames.py) or [GitHub issues](https://github.com/WordPress/openverse/blob/331b576ad8dd99dc00c6a777a3b3addc6dbd3225/documentation/_ext/link_issues.py). We would have a similar extension which would rewrite unformatted links to the formatted version in the produced HTML files.

## Alternatives

Leave this without a check and occasionally audit the project to ensure all links in the documentation are clickable.

**Comment by sarayourfriend** [comment] 2024-04-25 22:24
Okay, I wrote a summary of how to accomplish this with Vale, but it occurred to me that it was weird MyST didn't already behave this way to begin with, and sure enough it has a syntax extension that does this for you: https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#linkify

We just need to enable that extension :slightly_smiling_face:

<details>
<summary>Here's what I originally wrote, just in case it is relevant for some reason, but unless the MyST extension doesn't do what we need, this bit shouldn't matter.</summary>

The Sphinx approach is definitely doable, but will incur an cost in our docs build time _every time_, so I'd rather try other approaches. I won't cover how I'd approach that because (a) it's almost certainly complicated and (b) for me to describe it would require sitting down and probably just doing it a.k.a., exploratory coding. If we do it with Sphinx, I don't think this is a good issue for someone who hasn't already worked on a Sphinx plugin before. Vale is a strong preference for me, it should be much simpler to do it there, if it is possible to do.

For Vale, first check out the documentation on writing Vale styles and the different possibilities: https://vale.sh/docs/topics/styles/

It should be possible to use a regex to find instances of raw links that are not wrapped in angle brackets, something like: `\shttps?://.[^>]?(\s|\.)`. The idea being: match the scheme with whitespace in front and terminating in either whitespace or a period, and allowing anything before the period/space other than `>` to avoid `>.` and `> ` matching; almost certainly doesn't work exactly, but it is where I would start.

I'm guessing that the "conditional" or "existence" style forms are the mostly likely to work for this.

One more thing to keep in mind, is that Vale has different "scopes" for rules, and we'll probably need to choose a more specific scope than the defaults to avoid false positives (specifically inside of code blocks): https://vale.sh/docs/topics/scoping/. IIRC this is why the [Openverse/TermCasing](https://github.com/WordPress/openverse/blob/b09b8652b93e10451741743b9c556503443252d1/.vale/styles/Openverse/TermCasing.yml#L8) style targets the `text` scope.
</details>

**Comment by madewithkode** [comment] 2024-04-26 07:57
I would love to take on this. Currently trying my hands on #3847

**Comment by sarayourfriend** [comment] 2024-04-26 09:33
Great, thanks @madewithkode, no rush at all on this one :+1:

**Comment by madewithkode** [comment] 2024-05-02 15:16
Hi @sarayourfriend @AetherUnbound resolving this issue is likely to render  the changes made in https://github.com/WordPress/openverse/pull/4195 redundant. What would you advise in respect to that?

1. Revert those changes in this MR
2. Leave as is
3. Revert the changes in a separate dedicated issue

**Comment by AetherUnbound** [comment] 2024-05-02 18:25
As long as the current syntax works in both cases (the docs site and in Airflow's markdown renderer), I think leaving as-is is fine!

**Comment by madewithkode** [comment] 2024-05-03 09:27
@AetherUnbound I have confirmed it works for the doc site, how do I check for(where do I find) Airflow's markdown renderer?

**Comment by dhruvkb** [comment] 2024-05-03 09:52
I looked into the Airflow instance and confirmed that the links are rendered properly. You can verify the same on your local Airflow instance, which can be started by following the [catalog quickstart guide](https://github.com/wordpress/openverse/blob/main/documentation/catalog/guides/quickstart.md).

![image](https://github.com/WordPress/openverse/assets/16580576/41f5165c-d1ef-40df-bf37-dbffef63600a)

**Comment by madewithkode** [comment] 2024-05-03 13:15
Thanks @dhruvkb. I have been able to verify this as well.

**Closed** 2024-05-05 13:06 UTC
Labels: help wanted, 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement, 🐍 tech: python, 🧱 stack: documentation
