### ISSUE TITLE
CI/CD mermaid diagram does not work in Firefox

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#2047] opened 2023-05-06 03:22 UTC
## Description

The mermaid diagram for the CI/CD docs page doesn't load properly on Firefox: https://docs.openverse.org/meta/ci_cd/jobs/api.html

## Reproduction

1. Load https://docs.openverse.org/meta/ci_cd/jobs/api.html in Firefox and see the above error.
2. Try again in Chrome and see that it loads properly

## Screenshots

**Failed (Firefox)**

![image](https://user-images.githubusercontent.com/10214785/236596149-f336d8aa-bea7-4710-961a-538eb87256c0.png)

**Working (Chrome)**

![image](https://user-images.githubusercontent.com/10214785/236596188-845269c5-137f-4e02-b965-f492ca558472.png)

**Comment by dhruvkb** [comment] 2023-05-06 04:58
I found that it's caused by this line. Apparently, Firefox cannot render line-labels to nodes with height of 0.

https://github.com/WordPress/openverse/blob/b172950486dcb690adf228375247ce7a150ab847/documentation/meta/ci_cd/jobs/api.md?plain=1#L11

However this diagram adds nothing more of value than already exists in `flow.md` so the best course of action would be to yeet it altogether.

**Comment by harsitagarwalla187** [comment] 2023-05-06 05:57
@dhruvkb Removing the line style x height:0 will work?

**Comment by dhruvkb** [comment] 2023-05-06 07:32
@harsitagarwalla187 yes, but the recommended solution is to delete the `{mermaid}` block entirely.

**Comment by harsitagarwalla187** [comment] 2023-05-06 07:44
@dhruvkb Ok. Can you assign it to me?

**Closed** 2023-05-08 12:52 UTC
Labels: good first issue, help wanted, 🟩 priority: low, 🛠 goal: fix, 📄 aspect: text, 🧱 stack: documentation
