### ISSUE TITLE
How we handle data integrity issues across the stack

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#292] opened 2022-08-18 13:33 UTC
## Due date: 2022-10-18

I'm not sure what a due date would be for this. Two weeks? What do y'all think.

## Assigned reviewers

- [ ] @krysal 
- [ ] @stacimc 

## Description
Is there anyone who has a comprehensive enough view to describe the process by which data integrity issues should be fixed? I am very concerned by the implications of the information in this discussion.

Sentiments like "no part of the stack guarantees the shape of its data" concerns me because we control every part of the stack in question. We have complete control over the shape of data in the Catalogue (up unto the point of actually receiving the information from the provider) and the API itself acts as yet another layer of transformation that I would hope would have a stable guaranteed surface. Something like licensing information, given it's a central aspect of why Openverse exists at all seems to be at least the bottom of what one should expect to be at all times supplied in full by the API and to exist in the catalogue.

Perhaps this also comes down, in some part, to API version guarantees that we are also murky on.

Does anyone have a holistic view of how we are meant to solve data integrity issues? If the frontend is broken due to an issue in the data returned by the API, do we take a step back and ask, "is the API returning this data because it itself is misbehaving, or is the data it's working off if incorrect (i.e., not properly ingested in the catalogue)"?

I am worried that we don't actually ask this question enough or potentially we do ask it but then do not document the fixes that need to be made upstream. One aspect of this I think is the inherent latency of issues as they flow from the catalogue to the API to the frontend. The frontend, right now, is very easy to deploy fixes to. The API is a little harder with a wide range depending on the severity of the change (migrations, column changes, etc). The catalogue is easy to deploy DAG fixes to, but the changes in the shape of the data may not make it down stream for at least a week if not longer depending on other issues in our data flow.

Do we need to have a more coordinated effort across the different parts of the stack to fix data integrity issues? How do we decide when and where to apply patches? If we hot fix things in the frontend (as is done in the PR linked above), should we do so with the expectation that the issue will be fixed upstream, whether the root cause is in the API or the catalogue? Should those hot fixes in the frontend or API eventually be slated for removal if their upstream dependencies they're compensating for get fixed?

My gut tells me that a process something like "hot fix it wherever makes the fix get out the soonest to the broadest set of clients" is probably the better answer, which would mean more work in the API than on the frontend to fix these things. Depending on the effort and complexity there maybe moving the fix down into the frontend temporarily is beneficial. Always moving data integrity things up into the catalogue seems like a natural assumption, I don't know if it's necessarily one we're making. Maybe we are and I'm not connecting the dots though. In some sense, a monorepo would really help in here as we could have a single issue that tracks the fix as it makes its way through the application layers and gets patched, promoted, and removed once things are solidified upstream.

What do y'all think about this? Are there improvements to the process we can follow here?

**Comment by rwidom** [comment] 2022-08-18 17:16
I'm not sure how helpful this is, but [dbt has a feature for data testing](https://docs.getdbt.com/docs/building-a-dbt-project/tests), which I think could be really helpful for this issue if implemented well. The unit tests that we write in the catalog (and presumably across the stack) are fantastic for catching transformations that don't behave _as originally intended_, but not as good at catching things like changes in the data sources and/or the intentions and the ways that they may ripple across the stack. Maybe there is a way to do both--hot fixes downstream as needed, plus changes and data tests upstream to prevent issues in the future? There's a relationship here to both the need for and the ability to do large scale backfills as well, that I have not at all thought through.

**Comment by zackkrida** [comment] 2022-08-23 13:56
I agree with the sentiment shared so far, that we have a situation roughly like this:

```
Frontend          ~>     Catalog
Easy to hotfix    ~>     Hard to hotfix
Implementation    ~>     Source of Truth     
```

I'd like to follow a consistent system where any time we make an API or Frontend hotfix (and we should default to the API, _unless_ something is a critical frontend bug which will be deployed same-day), we need to make a corresponding catalog issue. The hotfix should explicitly say 'this is a hotfix for data integrity issue #{number}'.

It's become clear to me that the catalog is a 'living document' in that records constantly need to be updated, removed, and added (side note: I'd love to find a way to help Openverse be more of an archive that can track historical changes to records over time).

Most likely we need dags for doing polite, incremental reingestion and updating of existing data.

**Comment by krysal** [comment] 2022-08-31 20:46
The process that Sara describes is one I was already assuming in my head so I'm glad the discussion is open because it doesn't seem like we share the same vision _yet_ so we can make an agreement here.

Usually, I tend to prefer to fix the issue with data in its origin, so the order tends to be the following:
1. Provider script or ingestion process (Catalog)
2. API endpoint
3. Frontend page

> Does anyone have a holistic view of how we are meant to solve data integrity issues? If the frontend is broken due to an issue in the data returned by the API, do we take a step back and ask, "is the API returning this data because it itself is misbehaving, or is the data it's working off if incorrect (i.e., not properly ingested in the catalogue)"?
>
> I am worried that we don't actually ask this question enough or potentially we do ask it but then do not document the fixes that need to be made upstream.

This is one of my concerns too, when a data issue gets "fixed" in the frontend it usually hides the real problem, and the API or Catalog issues get deprioritized, delayed, and in some unfortunate cases, forgotten. Personally, I'd like to avoid the extra code (hotfixes) as it doubles the work, it needs tests and to be removed after the data is fixed on the origin, but I understand there are occasions where it is necessary.

> Do we need to have a more coordinated effort across the different parts of the stack to fix data integrity issues?

I 100% agree. The good part is that we have already planned an entire project to review these unusualities and so some time will be spent on stabilizing the data sources and removing duplicated code.

> How do we decide when and where to apply patches?

My vote is for always doing it where the root cause is, unless it's something critical or the solution is it is extremely difficult (e.g. adding or removing a column in prod db), in that case, look for an alternative solution in the next layer.

>  If we hot fix things in the frontend (as is done in the PR linked above), should we do so with the expectation that the issue will be fixed upstream, whether the root cause is in the API or the catalogue?

Yes, again, whenever is feasible.

One idea I have is to not deprioritize the issue(s) that address the upstream problem after shipping the hotfix. It should be `high` at minimum and included in the batch of assigned issues of the next meeting.

**Comment by zackkrida** [comment] 2022-10-04 20:26
@WordPress/openverse I have added a formal two week deadline and assigned @stacimc and @krysal as reviewers on this discussion. I'd like to quickly wrap this up so it doesn't block the data integrity project we intend to start ASAP.

**Comment by stacimc** [comment] 2022-10-04 22:21
Thanks @zackkrida, I had missed this one.

I agree that fixing data issues at the source of truth (in the Catalog) is imperative. I worry that it's optimistic to plan for this being the _only_ response, because fixes in the Catalog currently take quite a bit of time. When a data issue is fixed in code, at minimum we need all affected providers to re-run ingestion _and_ for a data refresh to complete. For dated DAGs this takes even longer, because we also need enough reingestion workflows to run to get coverage for old data. This is significant because it includes Flickr, and because we plan on making even more of our DAGs dated in the future (at minimum, Finnish Museum and Phylopic).

Realistically, I think we are going to continue needing to hotfix things on the frontend or API when we encounter critical issues (although hopefully less frequently after the planned stabilizing work as @krysal pointed out!). But I agree **100%** with @krysal's concerns about the deprioritization and delay of data fixes. Maybe some additional process could be helpful:

We could create a new GH Issue Type for data integrity issues. Perhaps this could live in the catalog, and the issue template should include relevant sections such as:
* A warning that hotfixes should be handled with care/only used for critical issues
* Links to any related hotfixes in other repos
* If a hotfix is linked, there should also be a link to a follow-up issue to remove the hotfix when possible

> One idea I have is to not deprioritize the issue(s) that address the upstream problem after shipping the hotfix. It should be high at minimum and included in the batch of assigned issues of the next meeting.

I love this suggestion! We could even automatically apply `priority: high` labels to the new Issue type, if we go that route. We could also add a line item to address these issues in the MSR/Community meeting documentation.

________

The alternative strategy to fixing data issues in the Catalog, which we have definitely utilized many times, is to manually alter the data in the production database. Historically we've done this when only small amounts of data were affected, but as @AetherUnbound pointed out recently, we also have some data that is not associated with provider scripts.

Especially as we move to create more dated DAGs, I would love to start thinking about how we might formalize this process. I don't think that should be blocking to the data integrity project, however.

**Comment by rwidom** [comment] 2022-10-04 22:39
I love this idea about the new kind of issue with links to the hotfixes for many reasons, but one is that it would increase transparency across the stack about how data is being used in the front end.

**Comment by zackkrida** [comment] 2022-10-06 16:25
Love your issue template idea @stacimc. An `aspect: data integrity` label automatically applied might be nice too so we can use it to track these issues cross-repo.

**Comment by AetherUnbound** [comment] 2022-10-06 18:53
+1 to the idea of an issue template, and thank you for bringing this up @sarayourfriend! On top of many of the issues that we've encountered with various providers, I think what continues to surprise us is just how heterogeneous the data in the catalog is. The commoncrawl data seems to be the most non-conformant, and as such would seem to deviate from our expectations the most. The `MediaStore` subclasses have been _supremely_ helpful for new ingestion, as it has performed the normalization of new data even before it gets written to a TSV file.

I think one thing we could apply both pre- _and_ post-normalization is [Great Expectations](https://greatexpectations.io/). I haven't used it in the past, but I've heard a lot of good things about it. The notion behind this project is that you can [declare expectations about your data](https://greatexpectations.io/expectations) and get alerted when those expectations are not met. This expectations can be way more than "is the data a reasonable type", you can expect things like column averages or standard deviations. They make not that anything which can be computed can be expected. One impediment to this would be how long some expectations might take to run on our relatively unoptimized catalog database; the good news here is that GE has some [great hookups for Airflow](https://docs.greatexpectations.io/docs/deployment_patterns/how_to_use_great_expectations_with_airflow/). This may even be a good way of assessing _what_ normalization needs to be performed: we could write our present expectations for the catalog data, then see how they actually shape up when run against the dataset!

**Comment by krysal** [comment] 2022-11-30 22:21
Going back to this, there seems to be a consensus around evaluating data integrity issues more carefully. **Hotfix things on the frontend are acceptable for `🔴 critical` issues with the expectation that the issue will be fixed upstream, whether the root cause is in the API or the catalog, and removed after the fix in the root has been applied.**

I created an issue to evaluate the tools suggested, dbt and Great Expectations, these look very interesting!
@stacimc @obulat please create the issues for the new issue template and to audit the data layer of the frontend respectively if you consider it useful.

I think we can close this. Thank you all for your opinions and suggestions!

**Closed by krysal** 2022-11-30 22:21 UTC
Labels: 🟧 priority: high, 💬 talk: discussion
