### ISSUE TITLE
Increase Metropolitan reingestion timeout

### ISSUE THREAD

**Issue by stacimc** [WordPress/openverse#1392] opened 2023-01-31 00:12 UTC
## Description

We have a number of failures in the `metropolitan_reingestion_workflow` caused by AirflowTaskTimeouts during the `pull_data` step.

Per context in [this comment](https://github.com/WordPress/openverse/issues/1392), it's possible this is being caused by the entire DAG timing out, rather than the individual task. We should investigate to make sure.

Possible fixes:
* Increasing the task timeout [here](https://github.com/WordPress/openverse-catalog/blob/main/openverse_catalog/dags/providers/provider_reingestion_workflows.py#L84), if indeed the `pull_data` step is timing out.
* Increase the `dagrun_timeout` of the entire DAG
* Decrease the number of reingestion days for Metropolitan by adjusting the `_list_length` fields in the (https://github.com/WordPress/openverse-catalog/blob/main/openverse_catalog/dags/providers/provider_reingestion_workflows.py#L80)

**Comment by AetherUnbound** [comment] 2023-04-26 17:46
Duplicate of #1293

**Closed by AetherUnbound** 2023-04-26 17:46 UTC
