### ISSUE TITLE
Django request ID logging not working

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#2656] opened 2023-07-17 00:45 UTC
## Description

Example production API log:

```
[2023-07-16 05:07:33,929 - elasticsearch - 288][WARNING] [none] POST http://<redacted Elasticsearch URL>/image/_search [status:N/A request:10.012s]
```

Note the `[none]` between the log level and `POST`. The request ID should be in that space.

## Environment

Observed in production logs

## Additional context

Marked high because it makes production request lifecycle debugging impossible

**Comment by dhruvkb** [comment] 2023-07-17 04:09
I think this is a duplicate of #2638.

**Closed** 2023-07-17 04:11 UTC
Labels: 🟧 priority: high, ⛔️ status: discarded, 🛠 goal: fix, 💻 aspect: code, 🧱 stack: api

**Comment by sarayourfriend** [comment] 2023-07-17 04:47
Thanks, I should have searched!
