### ISSUE TITLE
Consider moving Swagger docs into the general documentation site

### ISSUE THREAD

**Issue by krysal** [WordPress/openverse#1804] opened 2023-04-17 23:04 UTC
## Current Situation

Originally reported by @sarayourfriend:

> The API documentation site is harder to maintain and while the Swagger docs are "automatically generated", we hand maintain almost every single aspect of it in code (code that precludes us from using things like `reverse` to retrieve request paths due to circular imports and such). That is to say, the code isn't necessarily easier to maintain than just hand maintaining the documentation in Markdown.

## Suggested Improvement

Move the info and instructions from https://api.openverse.engineering/v1/ into https://docs.openverse.org/

## Benefit

> Alternatively, there may be some way to use Swagger to generate the documentation in a format that can be merged into the general documentation site.
> Merging them has the benefit of uniting more documentation into a single place. We would need to consider what alternative "landing" page we would use for the API if we did this.

**Comment by dhruvkb** [comment] 2023-04-23 09:44
This is a duplicate of #1240. Closing this because #1240 has had some discussion.

**Closed by dhruvkb** 2023-04-23 09:44 UTC
Labels: 🟩 priority: low, ⛔️ status: discarded, ✨ goal: improvement, 📄 aspect: text, 🧱 stack: documentation
