### ISSUE TITLE
Jamendo thumbnails are failing

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#871] opened 2023-03-08 16:46 UTC
## Description

No thumbnails from Jamendo audio are visible, despite being present on the foreign landing urls and having the links correctly stored in our database.

It is likely an error with our thumbnail service. CC @sarayourfriend who has worked on these types of issues before.

## Reproduction

1. Check Jamendo API results: https://api.openverse.engineering/v1/audio/?source=jamendo
2. Visit the foreign landing url; observe artwork.
3. Visit the same work in openverse at openverse.org/audio/{uuid}
4. Observe the artwork is missing
5. Visit the thumbnail at https://api.openverse.engineering/v1/audio/{uuid}/thumb/, observe error

## Environment

- Device: 
- OS: 
- Browser: 
- Version: 
- Other info:

**Comment by sarayourfriend** [comment] 2023-03-09 06:11
I am forwarding this issue to the folks who can find the exact error in Photon's logs. I'll update here when I hear back.

**Comment by sarayourfriend** [comment] 2023-03-09 06:19
Actually, looking further into it, it looks like the query param forwarding might be broken again. It should be easier to look into this way than just a Jamendo issue. See that the thumbnail URL fails for this NYPL result as well: https://api.openverse.engineering/v1/images/e450986f-9f46-4b7c-966d-015d8cd025c4/

cc @AetherUnbound we need to add the Photon authentication key to the ECS deployment.

**Comment by sarayourfriend** [comment] 2023-03-09 06:24
Reprioritised as critical as it is effecting all providers that use query params for image URLs.

**Comment by AetherUnbound** [comment] 2023-03-09 20:22
Per some coordination with the team behind Photon, it looks like this is an issue with the Jamendo URLs:
- https://usercontent.jamendo.com?type=album&id=190828&width=300&trackid=1725531 _(does not work)_
- https://usercontent.jamendo.com/?type=album&id=190828&width=300&trackid=1725531 _(works, note the trailing `/` before params)_

The former link when viewed directly gets forwarded to the latter. I suspect Photon is incapable of following redirects like that case. I will get a PR up for fixing this on the catalog, but we could mitigate this immediately on the API by changing the Jamendo thumbnail URLs. It appears that all of them have this issue:

```
deploy@localhost:openledger> select count(thumbnail) from audio where provider='jamendo';
+--------+
| count  |
|--------|
| 522272 |
+--------+
SELECT 1
Time: 0.340s

deploy@localhost:openledger> select count(thumbnail) from audio where provider='jamendo' and thumbnail not like '%/?%' limit 10;
+--------+
| count  |
|--------|
| 522272 |
+--------+
SELECT 1
Time: 0.376s
```

The following query should work:

```sql
UPDATE audio
SET thumbnail = replace(thumbnail, '?', '/?') 
WHERE provider='jamendo' and thumbnail not like '%/?%';
```

**Comment by stacimc** [comment] 2023-03-09 20:47
The plan sounds solid to me, @AetherUnbound 👍

+1 for mitigating this immediately in the API DB, particularly given the current status of the data refresh. SQL looks good and I did a quick test run in my local which worked well. As Jamendo is not a dated DAG we should be fine as long as we kick off a new DAG-run with the fix from https://github.com/WordPress/openverse-catalog/pull/1038 before the next data refresh ✔️ 

Just double checking, we now believe this _is_ limited to Jamendo and not other providers? (re [comment](https://github.com/WordPress/openverse/issues/871#issuecomment-1461358803))?

**Comment by AetherUnbound** [comment] 2023-03-09 20:52
Thanks for checking that Staci!

> Just double checking, we now believe this _is_ limited to Jamendo and not other providers? (re [comment](https://github.com/WordPress/openverse/issues/871#issuecomment-1461358803))?

Good question, I would not be surprised if other providers' thumbnails also had some redirect action happening (similar to Jamendo) but the NYPL link Sara mentioned above appears to be working at the moment. Additionally, it seems as though this is _not_ an issue with the query param forwarding as initially suspected, so in that sense I don't believe the issue affects all providers that have query params in their thumbnails. For instance, Rawpixel has query params in its thumbnail URLs and those links appear to be working as expected: https://api.openverse.engineering/v1/images/?source=rawpixel

I'll go ahead and run that update!

**Comment by AetherUnbound** [comment] 2023-03-09 20:57
Query ran successfully!

```sql
deploy@localhost:openledger> UPDATE audio
 SET thumbnail = replace(thumbnail, '?', '/?') 
 WHERE provider='jamendo' and thumbnail not like '%/?%';
You're about to run a destructive command.
Do you want to proceed? (y/n): y
Your call!
UPDATE 522272
Time: 81.498s (1 minute 21 seconds), executed in: 81.498s (1 minute 21 seconds)
```

From the looks of it, Jamendo thumbnails are working again 😄 

![image](https://user-images.githubusercontent.com/10214785/224156001-a2911b69-0b36-4b07-a8f4-1f8710ea4c17.png)

I'll wait to close this issue until the referenced PR for the catalog gets merged.

**Comment by AetherUnbound** [comment] 2023-03-09 22:19
Thanks to a suggestion from @stacimc, I've also updated the audioset thumbnails:

```sql
deploy@localhost:openledger> select thumbnail from audioset where provider='jamendo' limit 10;
+----------------------------------------------------------------+
| thumbnail                                                      |
|----------------------------------------------------------------|
| https://usercontent.jamendo.com?type=album&id=100007&width=300 |
| https://usercontent.jamendo.com?type=album&id=100008&width=300 |
| https://usercontent.jamendo.com?type=album&id=100009&width=300 |
| https://usercontent.jamendo.com?type=album&id=10001&width=300  |
| https://usercontent.jamendo.com?type=album&id=100010&width=300 |
| https://usercontent.jamendo.com?type=album&id=100013&width=300 |
| https://usercontent.jamendo.com?type=album&id=100018&width=300 |
| https://usercontent.jamendo.com?type=album&id=100020&width=300 |
| https://usercontent.jamendo.com?type=album&id=100023&width=300 |
| https://usercontent.jamendo.com?type=album&id=100026&width=300 |
+----------------------------------------------------------------+
SELECT 10
Time: 0.100s
deploy@localhost:openledger> UPDATE audioset
  SET thumbnail = replace(thumbnail, '?', '/?') 
  WHERE provider='jamendo' and thumbnail not like '%/?%';
 
You're about to run a destructive command.
Do you want to proceed? (y/n): y
Your call!
UPDATE 65524
Time: 1.811s (1 second), executed in: 1.811s (1 second)
deploy@localhost:openledger> select thumbnail from audioset where provider='jamendo' limit 10;
+-----------------------------------------------------------------+
| thumbnail                                                       |
|-----------------------------------------------------------------|
| https://usercontent.jamendo.com/?type=album&id=621&width=300    |
| https://usercontent.jamendo.com/?type=album&id=7218&width=300   |
| https://usercontent.jamendo.com/?type=album&id=82096&width=300  |
| https://usercontent.jamendo.com/?type=album&id=85802&width=300  |
| https://usercontent.jamendo.com/?type=album&id=89269&width=300  |
| https://usercontent.jamendo.com/?type=album&id=94523&width=300  |
| https://usercontent.jamendo.com/?type=album&id=96477&width=300  |
| https://usercontent.jamendo.com/?type=album&id=99293&width=300  |
| https://usercontent.jamendo.com/?type=album&id=99349&width=300  |
| https://usercontent.jamendo.com/?type=album&id=100007&width=300 |
+-----------------------------------------------------------------+
SELECT 10
Time: 0.113s
```

**Comment by AetherUnbound** [comment] 2023-03-13 18:32
I'm not sure what has happened, but this stopped working again. We'll need to look into it once more.

**Comment by AetherUnbound** [comment] 2023-03-13 19:29
This appears to be related to an outage on Jamendo's end! We'll continue to monitor just to ensure it's not a regression.

**Comment by AetherUnbound** [comment] 2023-03-14 15:26
It appears that Jamendo now issues redirects from `jamendo.com` to `www.jamendo.com`. For a similar reason as described above, I suspect those redirects are breaking our ability to retrieve thumbnails 😕 I'll look into this more, we may need to perform another update to the database/catalog.

**Comment by AetherUnbound** [comment] 2023-03-14 16:03
That's an excellent idea Krystle! Very similar to our dead link approach.

**Comment by AetherUnbound** [comment] 2023-03-14 16:09
I have updated this in the API database once more, and thumbnails are showing up again!
```sql
deploy@localhost:openledger> UPDATE audio
  SET thumbnail = replace(thumbnail, '?', '/?')
  WHERE provider='jamendo' and thumbnail not like '%/?%';
You're about to run a destructive command.
Do you want to proceed? (y/n): y
Your call!
UPDATE 522272
Time: 332.418s (5 minutes 32 seconds), executed in: 332.418s (5 minutes 32 seconds)
deploy@localhost:openledger> UPDATE audioset
   SET thumbnail = replace(thumbnail, '?', '/?')
   WHERE provider='jamendo' and thumbnail not like '%/?%';
You're about to run a destructive command.
Do you want to proceed? (y/n): y
Your call!
UPDATE 65524
Time: 9.491s (9 seconds), executed in: 9.491s (9 seconds)
```

I still need to update this in the catalog, but indeed the query for `audioset` will be more complicated [since it is a view](https://github.com/WordPress/openverse-catalog/blob/0728cdbe8b8ef4dc1037d877cfbf322f7252db1b/docker/local_postgres/0007_openledger_audio_view.sql#L109).

**Comment by zackkrida** [comment] 2023-03-14 16:09
The thumbnails are also cached indefinitely by cloudflare, which should be sufficient for any performance concerns!

**Comment by AetherUnbound** [comment] 2023-03-14 16:23
I was able to run the following successfully on the catalog as well:

```sql
deploy@localhost:openledger> UPDATE audio
  SET thumbnail = replace(thumbnail, '?', '/?')
  WHERE provider='jamendo' and thumbnail not like '%/?%';
UPDATE 522272
Time: 45.763s (45 seconds), executed in: 45.763s (45 seconds)

deploy@localhost:openledger> UPDATE audio
 SET audio_set = audio_set || ('{"thumbnail": "' || replace(audio_set ->> 'thumbnail', '?', '/?') || '"}')::jsonb
 WHERE provider='jamendo' and audio_set ->> 'thumbnail' not like '%/?%';
UPDATE 522272
Time: 38.924s (38 seconds), executed in: 38.924s (38 seconds)
```

<details> <summary>More info on the audio set query</summary>

You unfortunately can't set values in a JSONB field the same way, so [I used the suggestion here to concat JSONB objects](https://dba.stackexchange.com/a/295300).

```sql
deploy@localhost:openledger> SELECT audio_set ->> 'thumbnail'
 FROM audio
 WHERE provider='jamendo' and audio_set ->> 'thumbnail' not like '%/?%' limit 10;
 
+----------------------------------------------------------------+
| ?column?                                                       |
|----------------------------------------------------------------|
| https://usercontent.jamendo.com?type=album&id=128787&width=300 |
| https://usercontent.jamendo.com?type=album&id=128883&width=300 |
| https://usercontent.jamendo.com?type=album&id=128883&width=300 |
| https://usercontent.jamendo.com?type=album&id=128883&width=300 |
| https://usercontent.jamendo.com?type=album&id=128883&width=300 |
| https://usercontent.jamendo.com?type=album&id=128883&width=300 |
| https://usercontent.jamendo.com?type=album&id=128883&width=300 |
| https://usercontent.jamendo.com?type=album&id=128883&width=300 |
| https://usercontent.jamendo.com?type=album&id=128883&width=300 |
| https://usercontent.jamendo.com?type=album&id=128883&width=300 |
+----------------------------------------------------------------+
SELECT 10
Time: 0.077s

deploy@localhost:openledger> SELECT audio_set || ('{"thumbnail": "' || replace(audio_set ->> 'thumbnail', '?', '/?') || '"}')::jsonb
 FROM audio
 WHERE provider='jamendo' and audio_set ->> 'thumbnail' not like '%/?%' limit 10;
 
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ?column?                                                                                                                                                                                                                                                                                                                          |
|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| {"title": "Blasphemous Metal", "creator": "Brudywr", "thumbnail": "https://usercontent.jamendo.com/?type=album&id=128787&width=300", "creator_url": "https://www.jamendo.com/artist/360747/Brudywr", "foreign_identifier": "128787", "foreign_landing_url": "https://www.jamendo.com/album/128787/blasphemous-metal"}             |
| {"title": "Autumn Leaves 2013", "creator": "Jazz Friends", "thumbnail": "https://usercontent.jamendo.com/?type=album&id=128883&width=300", "creator_url": "https://www.jamendo.com/artist/365833/Jazz_Friends", "foreign_identifier": "128883", "foreign_landing_url": "https://www.jamendo.com/album/128883/autumn-leaves-2013"} |
| {"title": "Autumn Leaves 2013", "creator": "Jazz Friends", "thumbnail": "https://usercontent.jamendo.com/?type=album&id=128883&width=300", "creator_url": "https://www.jamendo.com/artist/365833/Jazz_Friends", "foreign_identifier": "128883", "foreign_landing_url": "https://www.jamendo.com/album/128883/autumn-leaves-2013"} |
| {"title": "Autumn Leaves 2013", "creator": "Jazz Friends", "thumbnail": "https://usercontent.jamendo.com/?type=album&id=128883&width=300", "creator_url": "https://www.jamendo.com/artist/365833/Jazz_Friends", "foreign_identifier": "128883", "foreign_landing_url": "https://www.jamendo.com/album/128883/autumn-leaves-2013"} |
| {"title": "Autumn Leaves 2013", "creator": "Jazz Friends", "thumbnail": "https://usercontent.jamendo.com/?type=album&id=128883&width=300", "creator_url": "https://www.jamendo.com/artist/365833/Jazz_Friends", "foreign_identifier": "128883", "foreign_landing_url": "https://www.jamendo.com/album/128883/autumn-leaves-2013"} |
| {"title": "Autumn Leaves 2013", "creator": "Jazz Friends", "thumbnail": "https://usercontent.jamendo.com/?type=album&id=128883&width=300", "creator_url": "https://www.jamendo.com/artist/365833/Jazz_Friends", "foreign_identifier": "128883", "foreign_landing_url": "https://www.jamendo.com/album/128883/autumn-leaves-2013"} |
| {"title": "Autumn Leaves 2013", "creator": "Jazz Friends", "thumbnail": "https://usercontent.jamendo.com/?type=album&id=128883&width=300", "creator_url": "https://www.jamendo.com/artist/365833/Jazz_Friends", "foreign_identifier": "128883", "foreign_landing_url": "https://www.jamendo.com/album/128883/autumn-leaves-2013"} |
| {"title": "Autumn Leaves 2013", "creator": "Jazz Friends", "thumbnail": "https://usercontent.jamendo.com/?type=album&id=128883&width=300", "creator_url": "https://www.jamendo.com/artist/365833/Jazz_Friends", "foreign_identifier": "128883", "foreign_landing_url": "https://www.jamendo.com/album/128883/autumn-leaves-2013"} |
| {"title": "Autumn Leaves 2013", "creator": "Jazz Friends", "thumbnail": "https://usercontent.jamendo.com/?type=album&id=128883&width=300", "creator_url": "https://www.jamendo.com/artist/365833/Jazz_Friends", "foreign_identifier": "128883", "foreign_landing_url": "https://www.jamendo.com/album/128883/autumn-leaves-2013"} |
| {"title": "Autumn Leaves 2013", "creator": "Jazz Friends", "thumbnail": "https://usercontent.jamendo.com/?type=album&id=128883&width=300", "creator_url": "https://www.jamendo.com/artist/365833/Jazz_Friends", "foreign_identifier": "128883", "foreign_landing_url": "https://www.jamendo.com/album/128883/autumn-leaves-2013"} |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
SELECT 10
Time: 0.081s
```

</details>

Closing this issue once more!

**Closed by AetherUnbound** 2023-03-14 16:23 UTC
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code, 🧱 stack: api

**Comment by krysal** [comment] 2023-03-14 21:12
Awesome! Thank you, @AetherUnbound ⭐️
